#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x4548B3A8C0D70C12 (john@szakmeister.net)
#
Name     : pypi-nose
Version  : 1.3.7
Release  : 86
URL      : https://files.pythonhosted.org/packages/58/a5/0dc93c3ec33f4e281849523a5a913fa1eea9a3068acfa754d44d88107a44/nose-1.3.7.tar.gz
Source0  : https://files.pythonhosted.org/packages/58/a5/0dc93c3ec33f4e281849523a5a913fa1eea9a3068acfa754d44d88107a44/nose-1.3.7.tar.gz
Source1  : https://files.pythonhosted.org/packages/58/a5/0dc93c3ec33f4e281849523a5a913fa1eea9a3068acfa754d44d88107a44/nose-1.3.7.tar.gz.asc
Summary  : nose extends unittest to make testing easier
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: pypi-nose-bin = %{version}-%{release}
Requires: pypi-nose-man = %{version}-%{release}
Requires: pypi-nose-python = %{version}-%{release}
Requires: pypi-nose-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
Patch1: doc-install.patch
Patch2: 0001-Disable-use_2to3-setuptools-option.patch

%description
it easier to write, find and run tests.
        
            By default, nose will run tests in files or directories under the current
            working directory whose names include "test" or "Test" at a word boundary
            (like "test_this" or "functional_test" or "TestClass" but not
            "libtest"). Test output is similar to that of unittest, but also includes
            captured stdout output from failing tests, for easy print-style debugging.
        
            These features, and many more, are customizable through the use of
            plugins. Plugins included with nose provide support for doctest, code
            coverage and profiling, flexible attribute-based test selection,
            output capture and more. More information about writing plugins may be

%package bin
Summary: bin components for the pypi-nose package.
Group: Binaries

%description bin
bin components for the pypi-nose package.


%package man
Summary: man components for the pypi-nose package.
Group: Default

%description man
man components for the pypi-nose package.


%package python
Summary: python components for the pypi-nose package.
Group: Default
Requires: pypi-nose-python3 = %{version}-%{release}

%description python
python components for the pypi-nose package.


%package python3
Summary: python3 components for the pypi-nose package.
Group: Default
Requires: python3-core
Provides: pypi(nose)

%description python3
python3 components for the pypi-nose package.


%prep
%setup -q -n nose-1.3.7
cd %{_builddir}/nose-1.3.7
%patch1 -p1
%patch2 -p1
pushd ..
cp -a nose-1.3.7 buildavx2
popd

%build
## build_prepend content
2to3 --write --nobackups .
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656391490
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test || :
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
## install_append content
ln -s nosetests %{buildroot}/usr/bin/nosetests-3
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/nosetests
/usr/bin/nosetests-3

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/nosetests.1

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
